# Generated by Django 5.1.6 on 2025-04-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_category_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '支払い待ち'), ('paid', '支払い済み'), ('preparing', '発送準備中'), ('shipped', '発送済み'), ('delivered', '配達済み'), ('cancelled', 'キャンセル済み')], default='pending', max_length=20, verbose_name='注文状態')),
                ('shipping_address', models.TextField(verbose_name='配送先住所')),
                ('total_price', models.PositiveIntegerField(verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='購入時の価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='注文')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文商品',
                'verbose_name_plural': '注文商品',
            },
        ),
    ]
